name: "Pull Request Automation"
on:
  pull_request_target:
    types: ["opened", "synchronize", "reopened", "edited", "labeled", "unlabeled"]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

  validate:
    runs-on: ubuntu-latest
    needs: label
    steps:
      - uses: OctoPrint/actions/pr-validation@dev
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          dry-run: false
