name: Handle releases
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-on-release:
    name: 📦 Publish on GitHub release
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Created dummy files
        run: |
          mkdir dist
          echo "foo" > foo.txt
          echo "bar" > bar.txt
      
      - name: ⬆ Upload to release
        run: |
          UPLOAD_URL="https://uploads.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets"
          for file in dist/*; do
            echo "Uploading $file..."
            curl -s -XPOST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: $(file -b --mime-type $file)" \
              --data-binary @$file \
              "$UPLOAD_URL?name=$(basename $file)"
          done
